schema_version = "1.0.0"
id = "tlfem_tool"
version = "1.0.0"
name = "TLFEM Tool"
tagline = "Tool to create TLFEM mesh data"
maintainer = "Dorival Pedroso"
type = "add-on"
tags = ["Mesh"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
